name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Flutter SDK
        uses: actions/checkout@v4
        with:
          repository: flutter/flutter
          ref: 3.32.8
          path: flutter-sdk

      - name: Add Flutter to PATH
        run: echo "::add-path::$(pwd)/flutter-sdk/bin"

      - name: Show Flutter version and doctor
        run: |
          flutter --version
          flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Check code formatting
        run: flutter format --set-exit-if-changed

      - name: Run tests
        run: flutter test

      - name: Build APK for Android
        run: flutter build apk --release